- name: Start Grafana container
  docker_container:
    name: grafana
    image: grafana/grafana-oss
    state: started
    ports:
      - "3000:3000"
- name: Create prometheus datasource
  grafana_datasource:
    name: "{{ item.name }}"
    grafana_url: "{{ grafana_url }}"
    grafana_user: "{{ grafana_user }}"
    grafana_password: "{{ grafana_password }}"
    ds_type: "{{ item.ds_type }}"
    ds_url: "{{ item.ds_url }}"
    state: present
  with_items: "{{ data_source }}"
